trigger: none

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
  ## overriding build number to release number
  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      targetType: 'inline'
      script: |
        echo "Release Version : "$(releaseVersion)
        Write-Host "##vso[build.updatebuildnumber]$(releaseVersion)"

    displayName: 'Updating build number'

  - task: Docker@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      containerRegistry: 'algonomy'
      repository: 'or-kc-theme'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: $(releaseVersion)
    displayName: 'Tag latest docker image'
