
trigger:
  - main

variables:
  # Define variables in Library section under pipelines

  - name: dockerRegistryServiceConnection
    value: 'Linear_ACR'

  # container registry endpoint
  - name: acrEndpoint
    value: 'linearsquared.azurecr.io'


pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      containerRegistry: $(dockerRegistryServiceConnection)
      repository: 'or-kc-theme'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: $(releaseVersion)
    displayName: 'Tag latest docker image'
